Django_LEVEL_FOUR/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    # path('', views.index, name="index"),
    path('relative/',views.relative_url_template, name="relative"),
    path('other/', views.other,name="other"),
]

Django_LEVEL_FOUR/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name="index"),
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),

]

Django_LEVEL_FOUR/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Django_LEVEL_FOUR/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {"name":"hello World!", "number":100}
    return render(request,'basic_app/index.html',context=context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative_url_template(request):
    return render(request,'basic_app/relative_url_template.html')
# def index(request):
#     return render(request,'basic_app/index.html')

Django_LEVEL_FOUR/learning_templates/templates/basic_app/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url "index" %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url "admin:index" %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url "basic_app:other" %}">Other</a></li>
          <li><a class="navbar-link" href="{% url "basic_app:relative" %}">Relative</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {# Anything outside of this will be inherited if you use extend.#}
        {% endblock %}
    </div>
</body>
</html>

Django_LEVEL_FOUR/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to My Homepage!</h1>
    <h1>Filter Method from HTML</h1>
    <h2>{{ name|upper }}</h2>
    <h2>{{ number|add:"50" }}</h2>
    <h2>{{ name|cut:"World" }}</h2>
    {% endblock %}

Django_LEVEL_FOUR/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to My others page!</h1>
    {% endblock %}

Django_LEVEL_FOUR/learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to My relative Page!</h1>
   <a href="{% url "basic_app:other" %}">Go to others page</a> 
   <a href="{% url "admin:index" %}">LINK TO ADMIN PAGE</a> 
   <a href="{% url "index" %}">LINK TO INDEX</a> 
    {% endblock %}