Django_learning_YouTube/First_Project/First_App/urls.py
from django.urls import path
from First_App import views

app_name = 'First'

urlpatterns =[
    path('', views.index, name = 'index'),
    path('post/<str:id>/', views.details, name = 'details'),
    path('new-url/', views.new_url_view, name = 'new_page_url'),
    path('old-url/', views.old_url_redirect, name = 'old_url'),
    # path('html-page/', views.Html_page, name = 'html_page')
]

Django_learning_YouTube/First_Project/First_Project/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'First_Project.views.custom_page_not_found_view'

urlpatterns = [
    path('', include('First_App.urls')),
    path('admin/', admin.site.urls),
]

Django_learning_YouTube/First_Project/First_App/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
import logging
# Create your views here.

posts=[
    {'id':1,'title': 'Post 1', 'content': 'Content for post 1'},
    {'id':2,'title': 'Post 2', 'content': 'Content for post 2'},
    {'id':3,'title': 'Post 3', 'content': 'Content for post 3'},
    {'id':4,'title': 'Post 4', 'content': 'Content for post 4'}
]
def index(request):
    App_Title = "Latest App"
    return render(request, 'First_App/index.html', {"App_Title":App_Title, 'posts': posts})

def details(request,id):
    post=next((item for item in posts if item['id']== int(id)), None)
    #----------debugging with logging module-----------
    # logger=logging.getLogger("TESTING")
    # logger.debug(f"Post with ID {post} not found")
    return render(request, 'First_App/details.html', {'post':post})

def old_url_redirect(request):
    return redirect(reverse('First:new_page_url'))

def new_url_view(request):
    return HttpResponse("This is the new URL.")

def Html_page(request):
    my_dict ={ 'insert_me': " Hello I am from views.py file"}
    return render(request, 'html/index.html', context=my_dict)

Django_learning_YouTube/First_Project/First_Project/views.py
from django.shortcuts import render

def custom_page_not_found_view(request, exception):
    return render(request, 'First_App/404.html', status=404)

Django_learning_YouTube/First_Project/templates/First_App/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
    <!-- Header Content-->
      {% include 'First_App/include/header.html' %}

     <!-- Body Content --> 
      {% block content %}
      {% endblock %}
      
    <!--Footer Content-->
      {% include 'First_App/include/footer.html' %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Django_learning_YouTube/First_Project/templates/First_App/details.html
{% extends 'First_App/base.html' %}


{% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}}</h1>
              <p class="text-muted">Posted on January 1, 2024</p>
              <img src="https://via.placeholder.com/800x400" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    <li><a href="./detail.html">Post 1</a></li>
                    <li><a href="./detail.html">Post 2</a></li>
                    <li><a href="./detail.html">Post 3</a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock %}
 

Django_learning_YouTube/First_Project/templates/First_App/include/footer.html
<footer class="bg-dark text-light p-3">
        <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2021 Company, Inc</span>
        </div>
    </footer>

Django_learning_YouTube/First_Project/templates/First_App/include/header.html
    <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h3>FirstApp</h3>
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="">Home</a>
                    <a class="text-light text-decoration-none" href="">About</a>
                    <a class="text-light text-decoration-none" href="">Contact</a>
                </div>
            </div>
        </div>
    </header>

Django_learning_YouTube/First_Project/templates/First_App/index.html
{% extends 'First_App/base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2 >{{App_Title}}</h2>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                      <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                  </div>
            </div>
        </div>
        <div class="row m-3">
            {% if posts %}
                {% for post in posts %}
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">{{post.title}}</h5>
                                    <p class="card-text">{{post.content}}</p>
                                    <div class="d-flex justify-content-between">
                                        <a href="{% url 'First:details' id=post.id %}">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">Sports</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>No Post Available</p>
            {% endif %} 
            <div class="col-12 my-3">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        <li class="page-item"><span class="page-link">Page 3 of 20.</span></li>
                        <li class="page-item">
                            <a class="page-link" href="?page=4" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page=20" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                
            </div>
        </div>
        <div class="row">
           
        </div>
        
    </div>
{% endblock %}
    
    